apiVersion: v1                    # API version
kind: Service                     # Type of kubernetes resource
metadata:
  name: bolbolestan-mysql         # Name of the resource
  labels:                         # Labels that will be applied to the resource
    app: bolbolestan-mysql
spec:
  ports:
    - port: 3306
  selector:                       # Selects any Pod with labels `app=bolbolestan-mysql`
    app: bolbolestan-mysql