apiVersion: v1
kind: PersistentVolumeClaim        # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata:                          # Claim name and labels
  name: mysql-pvc
  labels:
    app: bolbolestan-mysql
spec:                              # Access mode and resource limits
  storageClassName: hiops          # Request a certain storage class
  volumeMode: Filesystem        
  accessModes:
    - ReadWriteOnce                # ReadWriteOnce means the volume can be mounted as read-write by a single Node
  resources:
    requests:
      storage: 2000M